//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Co_ID { get; set; }
        public string Org_Name { get; set; }
        public string Org_Address { get; set; }
        public string Org_Type { get; set; }
        public Nullable<int> Org_ContactNumber { get; set; }
        public Nullable<int> Org_FaxNumber { get; set; }
        public string Org_Email { get; set; }
    }
}
