//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Adopter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adopter()
        {
            this.Adopter_Contract = new HashSet<Adopter_Contract>();
            this.Adoptions = new HashSet<Adoption>();
            this.Adopter_Relative = new HashSet<Adopter_Relative>();
            this.Foster_Care_Parent = new HashSet<Foster_Care_Parent>();

            
        }

        public IEnumerable<Title> Titles { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name="Adopter ID")]
        public int Adopter_ID { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Name")]
        [Required]
        public string Adopter_Name { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Surname")]
        public string Adopter_Surname { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Email")]
        [EmailAddress]
        public string Adopter_Email { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Title")]
        public Nullable<int> Title_ID { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Address")]
        public string Adopter_Address { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Postal Address")]
        public string Adopter_PostalAddress { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Home Number")]
        public string Adopter_HomeNumber { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Work Number")]
        public string Adopter_WorkNumber { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Cell Number")]
        public string Adopter_CellNumber { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Car Registration")]
        public string Adopter_CarRegistartion_Number { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Employer")]
        public string Adopter_Employer { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Status")]
        public Nullable<int> Adopter_Status_ID { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Amount of family members")]
        public Nullable<int> Amount_of_Family_Memebers { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Number of children")]
        public Nullable<int> No_of_Children { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Age of children")]
        public Nullable<int> Age_of_Children { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Is the property securely closed?")]
        public Nullable<bool> Property_Securely_Closed { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Does the property include a pool?")]
        public Nullable<bool> Properyty_Include_Pool { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Is the pool secured?")]
        public Nullable<bool> Pool_Secured { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Is there a shelter available for the animal?")]
        public Nullable<bool> Animal_Shelter_Available { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Do you have a sick animal?")]
        public Nullable<bool> Sick_Animal { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "What is the sick animal's diagnosis?")]
        public string Sick_Animal_Diagnosis { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Where will the animal sleep?")]
        public string Animal_Sleep_Location { get; set; }

        [System.ComponentModel.DataAnnotations.Display(Name = "Have you given an animal away?")]
        public Nullable<bool> Given_Animal_Away { get; set; }

        
        public string HomeCheck_Suburb { get; set; }
        public string Type_of_House { get; set; }
        public Nullable<bool> Adopted_Before { get; set; }
        public Nullable<bool> Complex_or_Flat { get; set; }
        public Nullable<bool> Animal_Allowed { get; set; }
        public string Animal_Captivity { get; set; }
        public Nullable<bool> Animal_Vaccines_Updated { get; set; }


        [System.ComponentModel.DataAnnotations.Display(Name = "Adopter Title")]
        public virtual Title Title { get; set; }

        public virtual Adopter_Status Adopter_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopter_Contract> Adopter_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopter_Relative> Adopter_Relative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foster_Care_Parent> Foster_Care_Parent { get; set; }
    }
}
