//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdoptionPayment
    {
        public int AdoptionPaymentID { get; set; }
        public Nullable<int> Adoption_ID { get; set; }
        public Nullable<int> Animal_Type_ID { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<decimal> Adoption_Fee { get; set; }
    
        public virtual Adoption Adoption { get; set; }
        public virtual Animal_Type Animal_Type { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
    }
}
