//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;  //needed for Display annotation
    using System.ComponentModel;  //DisplayName annotation

    public partial class Adopter_Contract
    {
        [Display(Name = "Contract")]
        public int Contract_ID { get; set; }

        [Display(Name = "Electronic Contract Details")]
        [Required]
        public string Electronic_Contract { get; set; }


        [Display(Name = "Adopter")]
        public Nullable<int> Adopter_ID { get; set; }


        [Display(Name = "Adopter")]
        public virtual Adopter Adopter { get; set; }
    }
}