//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timer
    {
        public int Timer_Id { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> Seconds { get; set; }
    }
}
