//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;  //needed for Display annotation
    using System.ComponentModel;  //DisplayName annotation

    public partial class Volunteer_Hours
    {
        [Display(Name = "Volunteer Hours")]
        public int Vol_Hours_ID { get; set; }


        [Display(Name = "Volunteer Work Date")]
        [Required]
        public Nullable<System.DateTime> Vol_workDate { get; set; }


        [Display(Name = "Volunteer Start Time")]
        [Required]
        public Nullable<System.DateTime> Vol_Start_Time { get; set; }


        [Display(Name = "Volunteer End Time")]
        [Required]
        public Nullable<System.DateTime> Vol_End_Time { get; set; }


        [Display(Name = "Volunteer")]
        public Nullable<int> Vol_ID { get; set; }


        [Display(Name = "Volunteer Work Type")]
        public Nullable<int> Vol_WorkType_ID { get; set; }


        [Display(Name = "Volunteer")]
        public virtual Volunteer Volunteer { get; set; }


        [Display(Name = "Volunteer Work Type")]
        public virtual Volunteer_Work_Type Volunteer_Work_Type { get; set; }
    }
}
